### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nitrocode** [rpatrick00/terraform-provider-environment#6]
Hi. Thank you for maintaining this repo. I noticed some PRs went in recently #3 #4 #5 .

Would it be ok to release a new version or are there more changes planned for the next release?

**Comment by nitrocode** [comment]
cc: @rpatrick00

**Comment by robertpatrick** [comment]
I am happy to merge and release as needed.  Just let me know.

**Comment by nitrocode** [comment]
Thank you @robertpatrick for the quick response! could we release version 0.9.1 or 0.10.0 after the recent changes that merged in?

**Comment by rpatrick00** [comment]
v0.10.0 released
